name: graffity_viewer
description: Graffity Viewer Application.
publish_to: "none"
version: 3.2.1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  flutter_native_splash: ^2.4.0
  mobile_scanner: ^4.0.1
  go_router: ^13.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/g_viewer_logo.png"
  min_sdk_android: 28

flutter:
  uses-material-design: true

  assets:
    - assets/images/
