name: graffity_viewer
description: Graffity Viewer Application.
publish_to: "none"
version: 3.4.3+34301

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.0
  mobile_scanner: ^6.0.10
  go_router: ^15.1.2
  # firebase_core: ^3.13.0
  # firebase_crashlytics: ^4.3.5
  # firebase_analytics: ^11.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/g_viewer_logo.png"
  min_sdk_android: 28

flutter:
  uses-material-design: true

  assets:
    - assets/images/
